#!/usr/bin/env sh

message=$(head -n1 "$1")

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._-]+\))?!?: .+$'

if ! printf "%s" "$message" | grep -Eq "$pattern"; then
  echo "❌ Invalid commit message"
  echo "Example: feat(web): add login page"
  exit 1
fi